
* Overview

Just a collection of operations on a tagged union wrapping various
data structures for use in my own projects. Includes implementations
of:

- Counted Strings
- Counted Arrays
- Linked Lists
- [[https://github.com/tsoding/arena/][Arena Allocators]]
- [[https://nullprogram.com/blog/2023/09/30/][Hashmap Trie]]

It is all packaged as an [[https://github.com/nothings/stb/blob/master/docs/stb_howto.txt][STB-style single-header library]]

* Usage

To have access to the structs and function declarations, simply
include the file:

#+begin_src c
  #include "libblacksquid.h"
#+end_src

And the file that contains the main() function, define
LIBBLACKSQUID_IMPLEMENTATION and then include the file in order to
instantiate the implementation:

#+begin_src c
  #define LIBBLACKSQUID_IMPLEMENTATION
  #include "libblacksquid.h"
#+end_src

* LICENSE

Copyright 2024 theblacksquid

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
“Software”), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
